In [1]:
#(29/08/2022) Monday

# Let's Explore:

#### The Rise of Mughal Dynasty:

<a href='https://en.wikipedia.org/wiki/Akbar' target='_blank'> Akbar I </a>

<img src=''>

<img src='https://upload.wikimedia.org/wikipedia/commons/2/2e/Posthumous_portrait_of_Mughal_Empreror_Akbar.jpg' width=700px>

Abu'l-Fath Jalal-ud-din Muhammad Akbar, popularly known as Akbar the Great, and also as Akbar I, was the third Mughal emperor, who reigned from 1556 to 1605. Akbar succeeded his father, Humayun, under a regent, Bairam Khan, who helped the young emperor expand and consolidate Mughal domains in India

In [2]:
# Let's get started

# Numpy array basic Indexing and Slicing:

In [3]:
import numpy as np

In [4]:
arr2d = np.arange(25).reshape(5,5)  

In [5]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [6]:
arr2d[2][3]

13

In [7]:
arr3d = np.arange(64).reshape(4,2,8)  

In [8]:
arr3d

array([[[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15]],

       [[16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31]],

       [[32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47]],

       [[48, 49, 50, 51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60, 61, 62, 63]]])

In [9]:
arr3d[2][1][6]

46

In [10]:
arr3d[2,1,6]

46

In [11]:
arr4d = np.arange(128).reshape(4,2,8,2)

In [12]:
arr4d

array([[[[  0,   1],
         [  2,   3],
         [  4,   5],
         [  6,   7],
         [  8,   9],
         [ 10,  11],
         [ 12,  13],
         [ 14,  15]],

        [[ 16,  17],
         [ 18,  19],
         [ 20,  21],
         [ 22,  23],
         [ 24,  25],
         [ 26,  27],
         [ 28,  29],
         [ 30,  31]]],


       [[[ 32,  33],
         [ 34,  35],
         [ 36,  37],
         [ 38,  39],
         [ 40,  41],
         [ 42,  43],
         [ 44,  45],
         [ 46,  47]],

        [[ 48,  49],
         [ 50,  51],
         [ 52,  53],
         [ 54,  55],
         [ 56,  57],
         [ 58,  59],
         [ 60,  61],
         [ 62,  63]]],


       [[[ 64,  65],
         [ 66,  67],
         [ 68,  69],
         [ 70,  71],
         [ 72,  73],
         [ 74,  75],
         [ 76,  77],
         [ 78,  79]],

        [[ 80,  81],
         [ 82,  83],
         [ 84,  85],
         [ 86,  87],
         [ 88,  89],
         [ 90,  91],
         [ 92,  93],

In [13]:
arr4d[3][0][0][1]

97

In [14]:
arr4d[3,0,0,1]

97

In [15]:
#Slicing for more values:

In [16]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [17]:
# To access [11, 12, 13]

# [start-row:end-row, start-column:end-column ]

In [18]:
arr2d[2:3,1:4]

array([[11, 12, 13]])

In [19]:
arr2d[0:5, 4:5]

array([[ 4],
       [ 9],
       [14],
       [19],
       [24]])

In [20]:
arr2d[0,2:4]

array([2, 3])

In [21]:
arr2d[0:,4:]

array([[ 4],
       [ 9],
       [14],
       [19],
       [24]])

In [22]:
# To access [16, 17, 18, 19]
print(arr2d)
arr2d[3:4,1:4]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[16, 17, 18]])

In [23]:
# OR

print(arr2d[1:4,1:4])

arr2d[3:4,1:4]

[[ 6  7  8]
 [11 12 13]
 [16 17 18]]


array([[16, 17, 18]])

In [24]:
# 1d mein no rows and no columns
arr1d = np.arange(10)
print(arr1d)

[0 1 2 3 4 5 6 7 8 9]


<img src='https://tutorialspoint.dev/image/Numpy1.jpg' width=500px>

<img src='https://res.cloudinary.com/dyd911kmh/image/upload/v1651825496/content_arrays_axes_8d6a639e44.png' width=500px>

<img src='https://miro.medium.com/max/1400/0*7mdPBssk30gaDfKm.png' width=500px>

In [25]:
print(arr1d)
arr2d = arr1d.reshape(2,5)
print(arr2d)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [26]:
print('######################## 1d #################### \n')
# Cann't be convered from arr2d as the format doesn't fufills the requirement slicing:
arr1d = np.arange(16)
print(arr1d)
print('\n ######################## 2d #################### \n')
arr2d = arr1d.reshape(2,8)
print(arr2d)
arr3d = arr1d.reshape(4,2,2)
print('\n ######################## 3d #################### \n')
print(arr3d)
print(type(arr3d))

######################## 1d #################### 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

 ######################## 2d #################### 

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]

 ######################## 3d #################### 

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]]
<class 'numpy.ndarray'>


In [27]:
mydata=np.arange(20).reshape(5,4)
mydata

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [28]:
# creating random number list from list:

mydata[[4,2,0]]

array([[16, 17, 18, 19],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3]])

In [29]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names =='Bob'

array([ True, False, False,  True, False, False, False])

In [30]:
mydata[[True, False, True,  False, True]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])

In [31]:
mydata >= 10

array([[False, False, False, False],
       [False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [32]:
mydata[mydata >= 10]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [33]:
mydata[(mydata >= 10) & (mydata <= 15)]

array([10, 11, 12, 13, 14, 15])

In [34]:
newdata = np.arange(100).reshape(10,10)
print(newdata)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [35]:
newdata > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [36]:
# We're checking a condition inside our dataset!
newdata[newdata > 50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [37]:
newdata[newdata%2!=0]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [38]:
# We're checking if any of our condition is true inside our dataset!
newdata[(newdata >= 50) & ((newdata == 60) | (newdata <= 70))]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70])

In [39]:
newdata[(newdata%2!=0) & (newdata%3==0)]

array([ 3,  9, 15, 21, 27, 33, 39, 45, 51, 57, 63, 69, 75, 81, 87, 93, 99])

In [40]:
data = np.array([2,5,3,8,9,10,12,20,0,1,23,67]).reshape(4,3)
print(len(data)) # 4 >> counting rows only
data[(data<5) & (data%2 == 0)]

4


array([2, 0])

In [41]:
data = np.array([2,5,3,8,9,10,12,20,0,1,23,67]).reshape(3,4)
print(len(data)) # 4 >> counting rows only
data[(data<5) & (data%2 == 0)]

3


array([2, 0])

# Fancy Indexing:

In [42]:
arr = np.arange(10)
print(arr)
inds = [7, 1, 2, 6]
arr[inds]

[0 1 2 3 4 5 6 7 8 9]


array([7, 1, 2, 6])

In [43]:
# Transpose: merger of arrays.
print(arr2d)
arr2d.T

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


array([[ 0,  8],
       [ 1,  9],
       [ 2, 10],
       [ 3, 11],
       [ 4, 12],
       [ 5, 13],
       [ 6, 14],
       [ 7, 15]])

In [44]:
#Done