In [1]:
import pandas as pd
import numpy as np

In [2]:
car = pd.read_csv('car_data.csv',header=0)

In [3]:
car.head()

name   company  year          Price  \
0    Hyundai Santro Xing XO eRLX Euro III   Hyundai  2007         80,000   
1                 Mahindra Jeep CL550 MDI  Mahindra  2006       4,25,000   
2              Maruti Suzuki Alto 800 Vxi    Maruti  2018  Ask For Price   
3  Hyundai Grand i10 Magna 1.2 Kappa VTVT   Hyundai  2014       3,25,000   
4        Ford EcoSport Titanium 1.5L TDCi      Ford  2014       5,75,000   

   kms_driven fuel_type  
0  45,000 kms    Petrol  
1      40 kms    Diesel  
2  22,000 kms    Petrol  
3  28,000 kms    Petrol  
4  36,000 kms    Diesel

In [4]:
car.shape

(892, 6)

In [5]:
car.year.unique()

array(['2007', '2006', '2018', '2014', '2015', '2012', '2013', '2016',
       '2010', '2017', '2008', '2011', '2019', '2009', '2005', '2000',
       '...', '150k', 'TOUR', '2003', 'r 15', '2004', 'Zest', '/-Rs',
       'sale', '1995', 'ara)', '2002', 'SELL', '2001', 'tion', 'odel',
       '2 bs', 'arry', 'Eon', 'o...', 'ture', 'emi', 'car', 'able', 'no.',
       'd...', 'SALE', 'digo', 'sell', 'd Ex', 'n...', 'e...', 'D...',
       ', Ac', 'go .', 'k...', 'o c4', 'zire', 'cent', 'Sumo', 'cab',
       't xe', 'EV2', 'r...', 'zest'], dtype=object)

In [6]:
car.Price.unique()

array(['80,000', '4,25,000', 'Ask For Price', '3,25,000', '5,75,000',
       '1,75,000', '1,90,000', '8,30,000', '2,50,000', '1,82,000',
       '3,15,000', '4,15,000', '3,20,000', '10,00,000', '5,00,000',
       '3,50,000', '1,60,000', '3,10,000', '75,000', '1,00,000',
       '2,90,000', '95,000', '1,80,000', '3,85,000', '1,05,000',
       '6,50,000', '6,89,999', '4,48,000', '5,49,000', '5,01,000',
       '4,89,999', '2,80,000', '3,49,999', '2,84,999', '3,45,000',
       '4,99,999', '2,35,000', '2,49,999', '14,75,000', '3,95,000',
       '2,20,000', '1,70,000', '85,000', '2,00,000', '5,70,000',
       '1,10,000', '4,48,999', '18,91,111', '1,59,500', '3,44,999',
       '4,49,999', '8,65,000', '6,99,000', '3,75,000', '2,24,999',
       '12,00,000', '1,95,000', '3,51,000', '2,40,000', '90,000',
       '1,55,000', '6,00,000', '1,89,500', '2,10,000', '3,90,000',
       '1,35,000', '16,00,000', '7,01,000', '2,65,000', '5,25,000',
       '3,72,000', '6,35,000', '5,50,000', '4,85,000', '3,29,5

In [7]:
car.kms_driven.unique()

array(['45,000 kms', '40 kms', '22,000 kms', '28,000 kms', '36,000 kms',
       '59,000 kms', '41,000 kms', '25,000 kms', '24,530 kms',
       '60,000 kms', '30,000 kms', '32,000 kms', '48,660 kms',
       '4,000 kms', '16,934 kms', '43,000 kms', '35,550 kms',
       '39,522 kms', '39,000 kms', '55,000 kms', '72,000 kms',
       '15,975 kms', '70,000 kms', '23,452 kms', '35,522 kms',
       '48,508 kms', '15,487 kms', '82,000 kms', '20,000 kms',
       '68,000 kms', '38,000 kms', '27,000 kms', '33,000 kms',
       '46,000 kms', '16,000 kms', '47,000 kms', '35,000 kms',
       '30,874 kms', '15,000 kms', '29,685 kms', '1,30,000 kms',
       '19,000 kms', nan, '54,000 kms', '13,000 kms', '38,200 kms',
       '50,000 kms', '13,500 kms', '3,600 kms', '45,863 kms',
       '60,500 kms', '12,500 kms', '18,000 kms', '13,349 kms',
       '29,000 kms', '44,000 kms', '42,000 kms', '14,000 kms',
       '49,000 kms', '36,200 kms', '51,000 kms', '1,04,000 kms',
       '33,333 kms', '33,600 kms', '5,

In [8]:
car.fuel_type.unique()

array(['Petrol', 'Diesel', nan, 'LPG'], dtype=object)

In [9]:
car.name.unique()

array(['Hyundai Santro Xing XO eRLX Euro III', 'Mahindra Jeep CL550 MDI',
       'Maruti Suzuki Alto 800 Vxi',
       'Hyundai Grand i10 Magna 1.2 Kappa VTVT',
       'Ford EcoSport Titanium 1.5L TDCi', 'Ford Figo', 'Hyundai Eon',
       'Ford EcoSport Ambiente 1.5L TDCi',
       'Maruti Suzuki Alto K10 VXi AMT', 'Skoda Fabia Classic 1.2 MPI',
       'Maruti Suzuki Stingray VXi', 'Hyundai Elite i20 Magna 1.2',
       'Mahindra Scorpio SLE BS IV', 'Audi A8', 'Audi Q7',
       'Mahindra Scorpio S10', 'Maruti Suzuki Alto 800',
       'Hyundai i20 Sportz 1.2', 'Maruti Suzuki Alto 800 Lx',
       'Maruti Suzuki Vitara Brezza ZDi', 'Maruti Suzuki Alto LX',
       'Mahindra Bolero DI', 'Maruti Suzuki Swift Dzire ZDi',
       'Mahindra Scorpio S10 4WD', 'Maruti Suzuki Swift Vdi BSIII',
       'Maruti Suzuki Wagon R VXi BS III',
       'Maruti Suzuki Wagon R VXi Minor',
       'Toyota Innova 2.0 G 8 STR BS IV', 'Renault Lodgy 85 PS RXL',
       'Skoda Yeti Ambition 2.0 TDI CR 4x2',
       'Maru

## Data post martem
    year :
           - year has so many issues 
           - all are in string obj not in date
    price: 
        - all are objects
        - digits separated in commas 
        - some values are characters
     kms_driven:
         - all are objects
        - digits separated in commas 
        - some values are characters
        - has nan values:
        
      fuel_type:
       - nan values
        
         
    name: 
     name is long inconsistent we will shorten it

In [10]:
# Data Cleaning
backup =car.copy()

In [11]:
car = car[car['year'].str.isnumeric()]

In [12]:
car.year= car['year'].astype(int)

In [13]:
car

name    company  year          Price  \
0      Hyundai Santro Xing XO eRLX Euro III    Hyundai  2007         80,000   
1                   Mahindra Jeep CL550 MDI   Mahindra  2006       4,25,000   
2                Maruti Suzuki Alto 800 Vxi     Maruti  2018  Ask For Price   
3    Hyundai Grand i10 Magna 1.2 Kappa VTVT    Hyundai  2014       3,25,000   
4          Ford EcoSport Titanium 1.5L TDCi       Ford  2014       5,75,000   
..                                      ...        ...   ...            ...   
886                    Toyota Corolla Altis     Toyota  2009       3,00,000   
888                     Tata Zest XM Diesel       Tata  2018       2,60,000   
889                      Mahindra Quanto C8   Mahindra  2013       3,90,000   
890                Honda Amaze 1.2 E i VTEC      Honda  2014       1,80,000   
891               Chevrolet Sail 1.2 LT ABS  Chevrolet  2014       1,60,000   

       kms_driven fuel_type  
0      45,000 kms    Petrol  
1          40 kms    Diesel  
2      22,000 kms    Petrol  
3      28,000 kms    Petrol  
4      36,000 kms    Diesel  
..            ...       ...  
886  1,32,000 kms    Petrol  
888    27,000 kms    Diesel  
889    40,000 kms    Diesel  
890        Petrol       NaN  
891        Petrol       NaN  

[842 rows x 6 columns]

In [14]:
car= car[car['Price'] !='Ask For Price']

In [15]:
car.Price

0        80,000
1      4,25,000
3      3,25,000
4      5,75,000
6      1,75,000
         ...   
886    3,00,000
888    2,60,000
889    3,90,000
890    1,80,000
891    1,60,000
Name: Price, Length: 819, dtype: object

In [16]:
car.Price  = car.Price.str.replace(',','').astype(int)

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\generic.py:5516: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value


In [17]:
car.kms_driven = car.kms_driven.str.split(' ').str.get(0).str.replace(',','')

In [18]:
car = car[car['kms_driven'].str.isnumeric()]

In [19]:
car['kms_driven'] = car['kms_driven'].astype(int)

In [20]:
car = car[~car['fuel_type'].isna()]

In [21]:
car['name'] = car['name'].str.split(' ').str.slice(0,3).str.join(' ')

In [22]:
car

name   company  year   Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
3         Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
4    Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
6                 Ford Figo      Ford  2012  175000       41000    Diesel
..                      ...       ...   ...     ...         ...       ...
883      Maruti Suzuki Ritz    Maruti  2011  270000       50000    Petrol
885          Tata Indica V2      Tata  2009  110000       30000    Diesel
886    Toyota Corolla Altis    Toyota  2009  300000      132000    Petrol
888            Tata Zest XM      Tata  2018  260000       27000    Diesel
889      Mahindra Quanto C8  Mahindra  2013  390000       40000    Diesel

[816 rows x 6 columns]

In [23]:
car = car.reset_index(drop=True)

In [24]:
car.describe()

year         Price     kms_driven
count   816.000000  8.160000e+02     816.000000
mean   2012.444853  4.117176e+05   46275.531863
std       4.002992  4.751844e+05   34297.428044
min    1995.000000  3.000000e+04       0.000000
25%    2010.000000  1.750000e+05   27000.000000
50%    2013.000000  2.999990e+05   41000.000000
75%    2015.000000  4.912500e+05   56818.500000
max    2019.000000  8.500003e+06  400000.000000

In [25]:
car

name   company  year   Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
2         Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
3    Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
4                 Ford Figo      Ford  2012  175000       41000    Diesel
..                      ...       ...   ...     ...         ...       ...
811      Maruti Suzuki Ritz    Maruti  2011  270000       50000    Petrol
812          Tata Indica V2      Tata  2009  110000       30000    Diesel
813    Toyota Corolla Altis    Toyota  2009  300000      132000    Petrol
814            Tata Zest XM      Tata  2018  260000       27000    Diesel
815      Mahindra Quanto C8  Mahindra  2013  390000       40000    Diesel

[816 rows x 6 columns]

In [26]:
car.to_csv('car_cleaned_data.csv')

In [27]:
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 816 entries, 0 to 815
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   name        816 non-null    object
 1   company     816 non-null    object
 2   year        816 non-null    int32 
 3   Price       816 non-null    int32 
 4   kms_driven  816 non-null    int32 
 5   fuel_type   816 non-null    object
dtypes: int32(3), object(3)
memory usage: 28.8+ KB


In [28]:
car.describe(include='all')

name company         year         Price     kms_driven  \
count                   816     816   816.000000  8.160000e+02     816.000000   
unique                  254      25          NaN           NaN            NaN   
top     Maruti Suzuki Swift  Maruti          NaN           NaN            NaN   
freq                     51     221          NaN           NaN            NaN   
mean                    NaN     NaN  2012.444853  4.117176e+05   46275.531863   
std                     NaN     NaN     4.002992  4.751844e+05   34297.428044   
min                     NaN     NaN  1995.000000  3.000000e+04       0.000000   
25%                     NaN     NaN  2010.000000  1.750000e+05   27000.000000   
50%                     NaN     NaN  2013.000000  2.999990e+05   41000.000000   
75%                     NaN     NaN  2015.000000  4.912500e+05   56818.500000   
max                     NaN     NaN  2019.000000  8.500003e+06  400000.000000   

       fuel_type  
count        816  
unique         3  
top       Petrol  
freq         428  
mean         NaN  
std          NaN  
min          NaN  
25%          NaN  
50%          NaN  
75%          NaN  
max          NaN

In [29]:
car=car[car['Price']<6e6]

In [30]:
car.describe(include='all')

name company         year         Price     kms_driven  \
count                   815     815   815.000000  8.150000e+02     815.000000   
unique                  254      25          NaN           NaN            NaN   
top     Maruti Suzuki Swift  Maruti          NaN           NaN            NaN   
freq                     51     221          NaN           NaN            NaN   
mean                    NaN     NaN  2012.442945  4.017933e+05   46277.096933   
std                     NaN     NaN     4.005079  3.815888e+05   34318.459638   
min                     NaN     NaN  1995.000000  3.000000e+04       0.000000   
25%                     NaN     NaN  2010.000000  1.750000e+05   27000.000000   
50%                     NaN     NaN  2013.000000  2.999990e+05   41000.000000   
75%                     NaN     NaN  2015.000000  4.900000e+05   56879.000000   
max                     NaN     NaN  2019.000000  3.100000e+06  400000.000000   

       fuel_type  
count        815  
unique         3  
top       Petrol  
freq         428  
mean         NaN  
std          NaN  
min          NaN  
25%          NaN  
50%          NaN  
75%          NaN  
max          NaN

In [31]:
car.Price.max()

3100000

In [32]:
car.Price.min()

30000

In [33]:
X=car[['name','company','year','kms_driven','fuel_type']].values
y=car['Price'].values

In [34]:
X

array([['Hyundai Santro Xing', 'Hyundai', 2007, 45000, 'Petrol'],
       ['Mahindra Jeep CL550', 'Mahindra', 2006, 40, 'Diesel'],
       ['Hyundai Grand i10', 'Hyundai', 2014, 28000, 'Petrol'],
       ...,
       ['Toyota Corolla Altis', 'Toyota', 2009, 132000, 'Petrol'],
       ['Tata Zest XM', 'Tata', 2018, 27000, 'Diesel'],
       ['Mahindra Quanto C8', 'Mahindra', 2013, 40000, 'Diesel']],
      dtype=object)

In [35]:
y

array([  80000,  425000,  325000,  575000,  175000,  190000,  830000,
        250000,  182000,  315000,  415000,  320000,   80000,  425000,
       1000000,  500000,  350000,  160000,  350000,  310000,   75000,
        100000,  100000,  100000,  190000,  290000,   95000,  180000,
        385000,  250000,  180000,  105000,  105000,  650000,  689999,
        448000,  549000,  501000,  489999,  280000,  250000,  349999,
        284999,  345000,  499999,  235000,  249999, 1475000,  180000,
        385000,  250000,  180000,  105000,  105000,  395000,  220000,
        170000,   85000,  175000,  190000,  200000,  830000,  200000,
        570000,  315000,  182000,  315000,  110000,  501000,  448999,
       1891111,  235000,  159500,  344999,  344999,  449999, 1891111,
        865000,  699000,  375000,  489999,  224999, 1200000,  195000,
        351000,  160000,  240000,   90000,  415000,  155000,  600000,
        189500,  350000,  210000,  390000,  135000, 1600000,  701000,
        265000,  525

In [36]:
y.shape

(815,)

In [37]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [38]:
from sklearn.linear_model import LinearRegression

In [39]:
from sklearn.preprocessing import OneHotEncoder

In [40]:
OneHotEncoder()


OneHotEncoder()

In [41]:
from sklearn.preprocessing import OneHotEncoder
from seaborn import load_dataset
df = load_dataset('penguins')

ohe = OneHotEncoder()
transformed = ohe.fit_transform(df[['island']])
print(transformed.toarray())
# Returns:# [[0. 0. 1.]#  [0. 0. 1.]#  [0. 0. 1.]#  ...#  [1. 0. 0.]#  [1. 0. 0.]#  [1. 0. 0.]]4
print(df.island.unique())
df

[[0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 ...
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
['Torgersen' 'Biscoe' 'Dream']


species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0    Adelie  Torgersen            39.1           18.7              181.0   
1    Adelie  Torgersen            39.5           17.4              186.0   
2    Adelie  Torgersen            40.3           18.0              195.0   
3    Adelie  Torgersen             NaN            NaN                NaN   
4    Adelie  Torgersen            36.7           19.3              193.0   
..      ...        ...             ...            ...                ...   
339  Gentoo     Biscoe             NaN            NaN                NaN   
340  Gentoo     Biscoe            46.8           14.3              215.0   
341  Gentoo     Biscoe            50.4           15.7              222.0   
342  Gentoo     Biscoe            45.2           14.8              212.0   
343  Gentoo     Biscoe            49.9           16.1              213.0   

     body_mass_g     sex  
0         3750.0    Male  
1         3800.0  Female  
2         3250.0  Female  
3            NaN     NaN  
4         3450.0  Female  
..           ...     ...  
339          NaN     NaN  
340       4850.0  Female  
341       5750.0    Male  
342       5200.0  Female  
343       5400.0    Male  

[344 rows x 7 columns]

In [42]:
print(ohe.categories_)

[array(['Biscoe', 'Dream', 'Torgersen'], dtype=object)]


#### the ColumnTransformer class to streamline the way in which you can one-hot encode data

In [43]:
# Using make_column_transformer to One-Hot Encode
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from seaborn import load_dataset
import pandas as pd
df = load_dataset('penguins')
df

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0    Adelie  Torgersen            39.1           18.7              181.0   
1    Adelie  Torgersen            39.5           17.4              186.0   
2    Adelie  Torgersen            40.3           18.0              195.0   
3    Adelie  Torgersen             NaN            NaN                NaN   
4    Adelie  Torgersen            36.7           19.3              193.0   
..      ...        ...             ...            ...                ...   
339  Gentoo     Biscoe             NaN            NaN                NaN   
340  Gentoo     Biscoe            46.8           14.3              215.0   
341  Gentoo     Biscoe            50.4           15.7              222.0   
342  Gentoo     Biscoe            45.2           14.8              212.0   
343  Gentoo     Biscoe            49.9           16.1              213.0   

     body_mass_g     sex  
0         3750.0    Male  
1         3800.0  Female  
2         3250.0  Female  
3            NaN     NaN  
4         3450.0  Female  
..           ...     ...  
339          NaN     NaN  
340       4850.0  Female  
341       5750.0    Male  
342       5200.0  Female  
343       5400.0    Male  

[344 rows x 7 columns]

In [44]:
transformer = make_column_transformer((OneHotEncoder(), ['island']),remainder='passthrough')

In [45]:
transformer

ColumnTransformer(remainder='passthrough',
                  transformers=[('onehotencoder', OneHotEncoder(), ['island'])])

In [46]:
transformed = transformer.fit_transform(df)

transformed

array([[0.0, 0.0, 1.0, ..., 181.0, 3750.0, 'Male'],
       [0.0, 0.0, 1.0, ..., 186.0, 3800.0, 'Female'],
       [0.0, 0.0, 1.0, ..., 195.0, 3250.0, 'Female'],
       ...,
       [1.0, 0.0, 0.0, ..., 222.0, 5750.0, 'Male'],
       [1.0, 0.0, 0.0, ..., 212.0, 5200.0, 'Female'],
       [1.0, 0.0, 0.0, ..., 213.0, 5400.0, 'Male']], dtype=object)

In [47]:
transformed_df = pd.DataFrame(transformed)
transformed_df

0    1    2       3     4     5      6       7       8
0    0.0  0.0  1.0  Adelie  39.1  18.7  181.0  3750.0    Male
1    0.0  0.0  1.0  Adelie  39.5  17.4  186.0  3800.0  Female
2    0.0  0.0  1.0  Adelie  40.3  18.0  195.0  3250.0  Female
3    0.0  0.0  1.0  Adelie   NaN   NaN    NaN     NaN     NaN
4    0.0  0.0  1.0  Adelie  36.7  19.3  193.0  3450.0  Female
..   ...  ...  ...     ...   ...   ...    ...     ...     ...
339  1.0  0.0  0.0  Gentoo   NaN   NaN    NaN     NaN     NaN
340  1.0  0.0  0.0  Gentoo  46.8  14.3  215.0  4850.0  Female
341  1.0  0.0  0.0  Gentoo  50.4  15.7  222.0  5750.0    Male
342  1.0  0.0  0.0  Gentoo  45.2  14.8  212.0  5200.0  Female
343  1.0  0.0  0.0  Gentoo  49.9  16.1  213.0  5400.0    Male

[344 rows x 9 columns]

In [48]:
df.transformed = pd.DataFrame(transformed)

C:\Users\LAB02R~1\AppData\Local\Temp/ipykernel_3432/3206416354.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df.transformed = pd.DataFrame(transformed)


In [49]:
df

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0    Adelie  Torgersen            39.1           18.7              181.0   
1    Adelie  Torgersen            39.5           17.4              186.0   
2    Adelie  Torgersen            40.3           18.0              195.0   
3    Adelie  Torgersen             NaN            NaN                NaN   
4    Adelie  Torgersen            36.7           19.3              193.0   
..      ...        ...             ...            ...                ...   
339  Gentoo     Biscoe             NaN            NaN                NaN   
340  Gentoo     Biscoe            46.8           14.3              215.0   
341  Gentoo     Biscoe            50.4           15.7              222.0   
342  Gentoo     Biscoe            45.2           14.8              212.0   
343  Gentoo     Biscoe            49.9           16.1              213.0   

     body_mass_g     sex  
0         3750.0    Male  
1         3800.0  Female  
2         3250.0  Female  
3            NaN     NaN  
4         3450.0  Female  
..           ...     ...  
339          NaN     NaN  
340       4850.0  Female  
341       5750.0    Male  
342       5200.0  Female  
343       5400.0    Male  

[344 rows x 7 columns]

### How to One-Hot Encode Multiple Columns with Scikit-Learn

In [50]:
# One-hot encoding multiple columns
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from seaborn import load_dataset
import pandas as pd
df = load_dataset('penguins')
df = df[['island', 'sex', 'body_mass_g']]
df = df.dropna()
transformer = make_column_transformer((OneHotEncoder(), ['island', 'sex']),remainder='passthrough')
transformed = transformer.fit_transform(df)
transformed_df = pd.DataFrame(transformed, columns=transformer.get_feature_names())
transformed_df.head()
# Returns:
#    onehotencoder__island_Biscoe  onehotencoder__island_Dream  ...  onehotencoder__sex_Male  remainder__body_mass_g
# 0                           0.0                          0.0  ...                      1.0                  3750.0
# 1                           0.0                          0.0  ...                      0.0                  3800.0
# 2                           0.0                          0.0  ...                      0.0                  3250.0
# 3                           0.0                          0.0  ...                      0.0                  3450.0
# 4                           0.0                          0.0  ...                      1.0                  3650.0


onehotencoder__x0_Biscoe  onehotencoder__x0_Dream  \
0                       0.0                      0.0   
1                       0.0                      0.0   
2                       0.0                      0.0   
3                       0.0                      0.0   
4                       0.0                      0.0   

   onehotencoder__x0_Torgersen  onehotencoder__x1_Female  \
0                          1.0                       0.0   
1                          1.0                       1.0   
2                          1.0                       1.0   
3                          1.0                       1.0   
4                          1.0                       0.0   

   onehotencoder__x1_Male  body_mass_g  
0                     1.0       3750.0  
1                     0.0       3800.0  
2                     0.0       3250.0  
3                     0.0       3450.0  
4                     1.0       3650.0