In [1]:
import numpy as np

In [2]:
my_arr = np.arange(1000000)

In [3]:
my_arr

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [4]:
my_list = list(range(1000000))

In [5]:
type(my_arr)

numpy.ndarray

In [6]:
my_arr.dtype

dtype('int32')

In [7]:
type(my_list)

list

In [8]:
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 13 ms


In [9]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 624 ms


In [10]:
data = np.random.randn(2,3)

In [11]:
data

array([[ 0.81209168, -1.69241856, -3.21285659],
       [-1.38619996,  0.62210889,  0.7878373 ]])

In [12]:
c=[[1,2,3,4,5,6,7],[1,2,3,4,5,6,7],[1,2,3,4,5,6,7]]
c

[[1, 2, 3, 4, 5, 6, 7], [1, 2, 3, 4, 5, 6, 7], [1, 2, 3, 4, 5, 6, 7]]

In [13]:
k = []
for i in c:
    for j in i:
        k.append(j*10)
        

In [14]:
a = []
for b in c:
    a.append(b*10)

In [15]:
k

[10,
 20,
 30,
 40,
 50,
 60,
 70,
 10,
 20,
 30,
 40,
 50,
 60,
 70,
 10,
 20,
 30,
 40,
 50,
 60,
 70]

In [16]:
a

[[1,
  2,
  3,
  4,
  5,
  6,
  7,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  1,
  2,
  3,
  4,
  5,
  6,
  7],
 [1,
  2,
  3,
  4,
  5,
  6,
  7,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  1,
  2,
  3,
  4,
  5,
  6,
  7],
 [1,
  2,
  3,
  4,
  5,
  6,
  7,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  1,
  2,
  3,
  4

In [17]:
c = np.random.randn(3,3)

In [18]:
c

array([[ 0.50895407,  1.32285225,  0.81672157],
       [ 0.53937055,  0.1719826 ,  0.41214724],
       [ 0.69929976, -0.04802436, -0.14254226]])

In [19]:
c*10 # vectorized operation

array([[ 5.0895407 , 13.22852254,  8.16721568],
       [ 5.39370549,  1.71982603,  4.12147238],
       [ 6.99299756, -0.48024361, -1.42542262]])

In [20]:
c+5

array([[5.50895407, 6.32285225, 5.81672157],
       [5.53937055, 5.1719826 , 5.41214724],
       [5.69929976, 4.95197564, 4.85745774]])

In [21]:
arr = np.arange(64).reshape(8,8)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [22]:
arr.shape

(8, 8)

In [23]:
arr.ndim

2

In [24]:
arr.dtype

dtype('int32')

In [25]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [26]:
arr3d = arr.reshape(4,8,2)#d,r,c

In [27]:
arr3d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29],
        [30, 31]],

       [[32, 33],
        [34, 35],
        [36, 37],
        [38, 39],
        [40, 41],
        [42, 43],
        [44, 45],
        [46, 47]],

       [[48, 49],
        [50, 51],
        [52, 53],
        [54, 55],
        [56, 57],
        [58, 59],
        [60, 61],
        [62, 63]]])

In [28]:
arr3d.ndim

3

In [29]:
z = np.array([[[[[[[[[[[[[[[[[[[[10]]]]]]]]]]]]]]]]]]]])

In [30]:
z

array([[[[[[[[[[[[[[[[[[[[10]]]]]]]]]]]]]]]]]]]])

In [31]:
z.ndim

20

In [32]:
np.zeros_like(arr3d)

array([[[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]]])

In [33]:
mat  = np.ones((4,5))*10
mat

array([[10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.]])

In [34]:
np.full((4,5),10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [35]:
np.eye(6,6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [36]:
a = np.array([[2,4,6,8],[1,3,5,7],[6,7,8,9]])

In [37]:
a[2,3]

9

In [38]:
a = np.arange(16).reshape(4, 4)

In [39]:
b = np.arange(16).reshape(4,4)

In [40]:
a*b

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225]])

In [41]:
%time a@b

Wall time: 0 ns


array([[ 56,  62,  68,  74],
       [152, 174, 196, 218],
       [248, 286, 324, 362],
       [344, 398, 452, 506]])

In [42]:
#Done