In [1]:
# Monday (22-Aug-2022) 

# Let's Explore:

### The Rise of Mughal Dynasty:


<a href='https://mg.wikipedia.org/wiki/Aurangzeb'>Aurangzeb Alamgir</a>

<img src='http://1.bp.blogspot.com/-r28ECCfkDng/UWEWrNLvgoI/AAAAAAAAAq8/ms3Q2WHQ3uU/s1600/Aurangzeb.jpg'>

Muhi al-Din Muhammad, commonly known as Aurangzeb and by his regnal title Alamgir, was the sixth emperor of the Mughal Empire, ruling from July 1658 until his death in 1707. Under his emperorship, the Mughals reached their greatest extent with their territory spanning nearly the entirety of South Asia.

Book Name: Python for Data Analysis: Data Wrangling with Pandas, NumPy, and IPython

<img src='https://wesmckinney.com/book/images/cover.png'>

Book Name : Learning Pandas by Michael Heydt
    
<img src='https://images-na.ssl-images-amazon.com/images/I/51Ulkyjm5fL._SX404_BO1,204,203,200_.jpg'>

In [2]:
#Linear Algebra : Matrices and vectors

pip = Package Manager. It is used to download certain packages of python to your computer.

In [3]:
# pip install package names

# Numpy:

'Numpy' stands for Numerical python

Written in C,C++, and many more.

In [4]:
import numpy as np

In [5]:
# as >> alias function : used to abbrev name. 

In [6]:
my_arr = np.arange(10000)

my_arr

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [7]:
my_list = list(range(10000))

my_list

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [8]:
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 996 µs


In [9]:
%time for _ in range(10): my_list2 = [x*2 for x in my_list]

Wall time: 3.99 ms


In [10]:
print(type(my_arr))

print(type(my_list))

print(type(range(10)))

<class 'numpy.ndarray'>
<class 'list'>
<class 'range'>


ndarray = n-dimesional-array(1d,2d,3d...)

In [11]:
data = np.random.randint(20,30)

In [12]:
data

29

In [13]:
# randint == random integer list.

In [14]:
data1 = np.random.randn(20,30)
data1

array([[ 1.59745753,  1.09256487,  0.82542387, -0.25150111, -0.25107557,
        -0.58146147, -0.55290916, -1.65988366, -0.25457978, -1.41567726,
        -0.44028955, -0.70195173,  0.69101239, -0.11636664,  0.79459425,
        -0.69330422, -0.43561229, -0.03460164,  0.43971504, -0.41960613,
        -0.21854265,  1.33367643,  0.04679211,  0.70950824, -1.12198451,
         0.01077437,  0.12959304, -0.96924261, -0.88041377,  0.40761256],
       [-0.08969696,  0.96047373, -1.34329398,  0.00766785,  1.65666971,
         0.01031966,  0.2682162 , -1.12619901, -0.8317613 ,  1.15114501,
         1.47796551,  0.65334286, -0.23775437,  0.2108961 ,  0.41611548,
        -1.25692296,  0.24746503,  0.03262489, -1.79879277, -1.20705545,
        -0.13551399, -1.82795579,  1.18687169,  0.16927133,  0.29100028,
         1.19999597, -1.43496406,  0.38499944, -1.45141782,  0.69630263],
       [-0.06833782, -3.52712647,  0.23226868, -0.49798277,  1.45348871,
         0.97940056, -0.65551704,  1.89508139,  1

In [15]:
# randn == random n number of list.

creates the list of 20 by 30

In [16]:
c = [[1,2,3,4,5,6,7],[1,2,3,4,5,6,7],[1,2,3,4,5,6,7]]

In [17]:
c

[[1, 2, 3, 4, 5, 6, 7], [1, 2, 3, 4, 5, 6, 7], [1, 2, 3, 4, 5, 6, 7]]

In [18]:
for i in c:
    
    print(i)

[1, 2, 3, 4, 5, 6, 7]
[1, 2, 3, 4, 5, 6, 7]
[1, 2, 3, 4, 5, 6, 7]


In [19]:
for i in c:
    for j in i:
        print(j)

1
2
3
4
5
6
7
1
2
3
4
5
6
7
1
2
3
4
5
6
7


# Scalar:

Mag but no direction


# Vector:

possess both.

<img src='vector.png'>

In [20]:
# Numpy supports vectorization over scalar quantity.

In [21]:
# with normal python, we cann't get the desired result(vectorize)

In [22]:
c

[[1, 2, 3, 4, 5, 6, 7], [1, 2, 3, 4, 5, 6, 7], [1, 2, 3, 4, 5, 6, 7]]

In [23]:
c*10

[[1, 2, 3, 4, 5, 6, 7],
 [1, 2, 3, 4, 5, 6, 7],
 [1, 2, 3, 4, 5, 6, 7],
 [1, 2, 3, 4, 5, 6, 7],
 [1, 2, 3, 4, 5, 6, 7],
 [1, 2, 3, 4, 5, 6, 7],
 [1, 2, 3, 4, 5, 6, 7],
 [1, 2, 3, 4, 5, 6, 7],
 [1, 2, 3, 4, 5, 6, 7],
 [1, 2, 3, 4, 5, 6, 7],
 [1, 2, 3, 4, 5, 6, 7],
 [1, 2, 3, 4, 5, 6, 7],
 [1, 2, 3, 4, 5, 6, 7],
 [1, 2, 3, 4, 5, 6, 7],
 [1, 2, 3, 4, 5, 6, 7],
 [1, 2, 3, 4, 5, 6, 7],
 [1, 2, 3, 4, 5, 6, 7],
 [1, 2, 3, 4, 5, 6, 7],
 [1, 2, 3, 4, 5, 6, 7],
 [1, 2, 3, 4, 5, 6, 7],
 [1, 2, 3, 4, 5, 6, 7],
 [1, 2, 3, 4, 5, 6, 7],
 [1, 2, 3, 4, 5, 6, 7],
 [1, 2, 3, 4, 5, 6, 7],
 [1, 2, 3, 4, 5, 6, 7],
 [1, 2, 3, 4, 5, 6, 7],
 [1, 2, 3, 4, 5, 6, 7],
 [1, 2, 3, 4, 5, 6, 7],
 [1, 2, 3, 4, 5, 6, 7],
 [1, 2, 3, 4, 5, 6, 7]]

In [24]:
# but, with numpy, we can:

<img src='box.png' width=50%>

<img src='https://cdn.educba.com/academy/wp-content/uploads/2019/11/multidimensional-array-in-java.png' width=50%>

<img src='https://i1.wp.com/indianaiproduction.com/wp-content/uploads/2019/06/NumPy-array.png?resize=640%2C307&ssl=1' width=50%>

<img src='https://cdn.educba.com/academy/wp-content/uploads/2019/09/3d-Arrays-in-Python-2.png' width=50%>

<img src='https://www.mathworks.com/help/examples/matlab/win64/nddemo_02.gif'>

In [25]:
z = np.arange(100)

In [26]:
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [27]:
z.ndim

1

In [28]:
x = np.array(10)

In [29]:
x

array(10)

In [30]:
x.ndim # 

0

In [31]:
s = np.array([[[[[[[[[[[[[[[[[[[[[[10]]]]]]]]]]]]]]]]]]]]]])

In [32]:
s

array([[[[[[[[[[[[[[[[[[[[[[10]]]]]]]]]]]]]]]]]]]]]])

In [33]:
s.ndim

22

<a href='https://www.youtube.com/watch?v=0tPFpL977eY'>That's how dimension looks.</a>

<a href='https://www.youtube.com/watch?v=Q_B5GpsbSQw'> For further reference, Check this out. </a>

View 'class27b(IntroToNumpy).ipynb' for complete info of Numpy lib!

In [34]:
#Done. 